server:
  port: 8761
eureka:
  client:

    # eureka server? eureka server?? ???? ??? ??? X
    register-with-eureka: false

    # eureka server? ?? microservice?? ?????(30???) ???? ??? ??? ??.
    fetch-registry: false