server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: gateway-server

  cloud:
    gateway:
      routes:
        - id: 1st-service-get
#          uri: http://localhost:58882/

          # 리우팅 될 마이크로서비스 application name을 작성(유레카 서버의 대쉬보드에서 이름 확인)
          uri: lb://1ST-SERVICE

          # 게이트웨이 요청이 아래와 같은 패턴으로 온다면(일종의 조건문)
          predicates:
            - Path=/first-service/**

          # 이후 라우팅 될 마이크로서비스에 /first-service라는 접두사가 제외되어 요청되게 할 내용 + 필터
          filters:
            - RewritePath=/first-service/(?<segment>. *), /$\{segment}
            - AddRequestHeader=first-request, first-request-header
            - AddResponseHeader=first-response, first-response-header

        - id: 2nd-service-get
#          uri: http://localhost:12345/
          uri: lb://2ND-SERVICE
          predicates:
            - Path=/second-service/**
          filters:
            - RewritePath=/second-service/(?<segment>. *), /$\{segment}